# Generated by Django 5.0.14 on 2025-12-11 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tryon", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tryonrequest",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tryonrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tryonrequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="tryonrequest",
            name="generated_image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
