# Generated by Django 5.0.14 on 2025-12-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tryon", "0002_tryonrequest_error_message_tryonrequest_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tryonrequest",
            name="task_id",
            field=models.CharField(
                blank=True,
                help_text="Celery task ID for tracking",
                max_length=255,
                null=True,
            ),
        ),
    ]
