# Generated by Django 5.0.14 on 2025-12-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SceneTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the scene template", max_length=255
                    ),
                ),
                (
                    "prompt",
                    models.TextField(help_text="Prompt description for the scene"),
                ),
                (
                    "sample_image",
                    models.ImageField(
                        blank=True,
                        help_text="Sample image for the scene template (optional)",
                        null=True,
                        upload_to="poses/scene_templates/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Scene Template",
                "verbose_name_plural": "Scene Templates",
                "ordering": ["-created_at"],
            },
        ),
    ]
