# Generated by Django 5.0.14 on 2025-12-10 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="scenetemplate",
            name="sample_image_url",
            field=models.URLField(
                blank=True,
                help_text="BunnyCDN URL for the sample image",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="scenetemplate",
            name="user",
            field=models.ForeignKey(
                default=1,
                help_text="User who created this scene template",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scene_templates",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="scenetemplate",
            name="sample_image",
            field=models.ImageField(
                blank=True,
                help_text="Sample image for the scene template (optional, local storage)",
                null=True,
                upload_to="poses/scene_templates/",
            ),
        ),
    ]
