# Generated by Django 5.0.14 on 2025-12-10 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poses", "0002_scenetemplate_sample_image_url_scenetemplate_user_and_more"),
        ("tryon", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TryonPoses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "generated_image_url",
                    models.URLField(
                        help_text="BunnyCDN URL for the generated pose image",
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scene_template",
                    models.ForeignKey(
                        help_text="The scene template used to generate this pose image",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scene_template_poses",
                        to="poses.scenetemplate",
                    ),
                ),
                (
                    "tryon",
                    models.ForeignKey(
                        help_text="The try-on request this pose image is based on",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pose_images",
                        to="tryon.tryonrequest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who generated this pose image",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tryon_poses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "TryOn Pose",
                "verbose_name_plural": "TryOn Poses",
                "ordering": ["-created_at"],
            },
        ),
    ]
