# Generated by Django 5.0.14 on 2025-12-11 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poses", "0003_tryonposes"),
    ]

    operations = [
        migrations.AddField(
            model_name="tryonposes",
            name="error_message",
            field=models.TextField(
                blank=True, help_text="Error message if generation failed", null=True
            ),
        ),
        migrations.AddField(
            model_name="tryonposes",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                help_text="Status of pose generation",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tryonposes",
            name="generated_image_url",
            field=models.URLField(
                blank=True,
                help_text="BunnyCDN URL for the generated pose image",
                max_length=500,
                null=True,
            ),
        ),
    ]
