# Generated by Django 5.0.14 on 2025-12-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poses", "0004_tryonposes_error_message_tryonposes_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tryonposes",
            name="task_id",
            field=models.CharField(
                blank=True,
                help_text="Celery task ID for tracking",
                max_length=255,
                null=True,
            ),
        ),
    ]
