# Generated by Django 5.2.9 on 2025-12-08 05:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(help_text="Current app version (e.g., '1.0.0', '1.2.3')", max_length=20, unique=True)),
                ('minimum_required_version', models.CharField(help_text="Minimum app version required to use the app (e.g., '1.0.0')", max_length=20)),
                ('force_update', models.BooleanField(default=False, help_text='If True, all apps must update (blocks all versions below current)')),
                ('is_active', models.BooleanField(default=True, help_text='If False, this version configuration is disabled')),
                ('release_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When this version was released')),
                ('release_notes', models.TextField(blank=True, help_text='Release notes or changelog for this version')),
                ('update_url', models.URLField(blank=True, help_text='URL where users can download/update the app (App Store, Play Store, etc.)')),
                ('update_message', models.TextField(blank=True, default='A new version of the app is available. Please update to continue using the app.', help_text='Message shown to users when update is required')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App Version',
                'verbose_name_plural': 'App Versions',
                'ordering': ['-release_date', '-version_number'],
            },
        ),
    ]
